logging:
  config: classpath:logback-spring.xml
spring:
  application:
    name: awin-test-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: awin_schema
  flyway:
    enabled: true
    schemas: awin_schema
    create-schemas: true
  security:
    user:
      name: admin
      password: password
