### Create a new todo
POST http://{{host}}/u2m/v1/todos
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "userid": {{userId}},
  "description": "Finish the test task",
  "icon": "task-icon",
  "state": false
}

> {%
    client.global.set("todoId", response.body.id);
%}

### Get all todos
GET http://{{host}}/u2m/v1/todos
Authorization: Basic {{username}} {{password}}

### Get todos for user
GET http://{{host}}/u2m/v1/todos?userid={{userId}}
Authorization: Basic {{username}} {{password}}

### Get todo by id
GET http://{{host}}/u2m/v1/todos/{{todoId}}
Authorization: Basic {{username}} {{password}}

### Update todo
PUT http://{{host}}/u2m/v1/todos/{{todoId}}
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "userid": {{userId}},
  "description": "Finish the test task - Updated",
  "icon": "task-icon-updated",
  "state": true
}

### Toggle todo state
PATCH http://{{host}}/u2m/v1/todos/{{todoId}}/toggle
Authorization: Basic {{username}} {{password}}

### Delete todo
DELETE http://{{host}}/u2m/v1/todos/{{todoId}}
Authorization: Basic {{username}} {{password}}
