### Create a new transaction
POST http://{{host}}/u2m/v1/transactions
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "userid": {{userId}},
  "value": 150.75,
  "details": "Online Shopping",
  "date": "2026-06-28T10:00:00Z"
}

> {%
    client.global.set("transactionId", response.body.id);
%}

### Get all transactions
GET http://{{host}}/u2m/v1/transactions
Authorization: Basic {{username}} {{password}}

### Get transactions for user
GET http://{{host}}/u2m/v1/transactions?userid={{userId}}
Authorization: Basic {{username}} {{password}}

### Get transaction by id
GET http://{{host}}/u2m/v1/transactions/{{transactionId}}
Authorization: Basic {{username}} {{password}}

### Update transaction
PUT http://{{host}}/u2m/v1/transactions/{{transactionId}}
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "userid": {{userId}},
  "value": 200.00,
  "details": "Online Shopping - Updated",
  "date": "2026-06-29T14:00:00Z"
}

### Delete transaction
DELETE http://{{host}}/u2m/v1/transactions/{{transactionId}}
Authorization: Basic {{username}} {{password}}
