### Create a new user
POST http://{{host}}/u2m/v1/users
Content-Type: application/json
X-Correlation-ID: {{correlationId}}

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "currency": "EUR"
}

> {% client.global.set("userId", response.body.userid); %}

### Get all users
GET http://{{host}}/u2m/v1/users
X-Correlation-ID: {{correlationId}}

### Get user by ID
GET http://{{host}}/u2m/v1/users/{{userId}}
X-Correlation-ID: {{correlationId}}

### Update user
PUT http://{{host}}/u2m/v1/users/{{userId}}
Content-Type: application/json
X-Correlation-ID: {{correlationId}}

{
  "name": "John Smith",
  "email": "john.smith@example.com",
  "currency": "GBP"
}

### Delete user
DELETE http://{{host}}/u2m/v1/users/{{userId}}
X-Correlation-ID: {{correlationId}}
